version: '3.8'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db-dev
      - redis
  db-dev:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_app
      - POSTGRES_PASSWORD=django_app
      - POSTGRES_DB=django_app_dev
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/data'

volumes:
  postgres_data:
  redis_data:
