version: 'Compose specification'

services:
  web:
    build:
      context: ./backend
    command: "/entrypoint.sh"
    restart: always
    ports:
      - $WEB_PORT:$WEB_PORT
    env_file:
      - .env
    environment:
      - SQL_HOST=db
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/data'

  celery:
    build:
      context: ./backend
    command: "/celery_start.sh"
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data: